import pandas as pd
from huggingface_hub import InferenceClient

# 1. Setup Client
HF_TOKEN = "YOUR_TOKEN_HERE"
client = InferenceClient(api_key=HF_TOKEN)

# 2. Load the file created by the summary generator
df = pd.read_csv('final_pro_analysis_with_summaries.csv')

# 3. Define the AI function
# This model classifies sentiment (POSITIVE or NEGATIVE)
def get_ai_insight(text):
    try:
        # We use a popular sentiment analysis model from Hugging Face
        results = client.text_classification(
            text, 
            model="distilbert/distilbert-base-uncased-finetuned-sst-2-english"
        )
        # Returns the label of the highest score
        return results[0]['label'] 
    except Exception as e:
        print(f"Error processing text: {e}")
        return "Unknown"

# 4. Apply to your column
# We are now targeting the 'match_summary' column generated by your previous script
print("Starting AI enrichment... this may take a moment.")
df['AI_Sentiment'] = df['match_summary'].apply(get_ai_insight)

# 5. Save the final enriched data
df.to_csv('final_pro_analysis_AI_Enriched.csv', index=False)
print("Enrichment complete! Saved to 'final_pro_analysis_AI_Enriched.csv'.")